In [1]:
import pandas as pd

In [2]:
df=pd.DataFrame()
df=pd.read_csv('puzzle_input.csv',encoding='UTF-8')
df

                                      Puzzle
0               ckmb52fldxkseven3fkjgcbzmnr7
1    gckhqpb6twoqnjxqplthree2fourkspnsnzxlz1
2                             2onetwocrgbqm7
3                  frkh2nineqmqxrvdsevenfive
4                                   four9two
..                                       ...
995                     5ppflb48tkcffone8six
996              five2two7hstbbqzrninegbtwo2
997                           eightfblzpmhs4
998               fbbdeightzzsdffh8jbjzxkclj
999                              3nine6five1

[1000 rows x 1 columns]

In [3]:
calibration=[]

for puzzle in df['Puzzle']:
    for i in range(0,len(puzzle),1):
        try:
            first_number=int(puzzle[i])
            break
        except:
            if puzzle[i] in ['o','t','f','s','e','n'] and len(puzzle[i:])>=3:
                first_number_str=puzzle[i]+puzzle[i+1]+puzzle[i+2]
                if first_number_str=='one':
                    first_number=1
                    break
                elif first_number_str=='two':
                    first_number=2
                    break
                elif first_number_str=='thr':
                    first_number=3
                    break
                elif first_number_str=='fou':
                    first_number=4
                    break
                elif first_number_str=='fiv':
                    first_number=5
                    break
                elif first_number_str=='six':
                    first_number=6
                    break
                elif first_number_str=='sev':
                    first_number=7
                    break
                elif first_number_str=='eig':
                    first_number=8
                    break
                elif first_number_str=='nin':
                    first_number=9
                    break
            pass
        
    for i in range(-1,-len(puzzle)-1,-1):
        try:
            second_number=int(puzzle[i])
            break
        except:
            if puzzle[i] in ['e','o','r','t','x','n'] and len(puzzle[:i])>=3:
                second_number_str=puzzle[i-2]+puzzle[i-1]+puzzle[i]
                if second_number_str=='one':
                    second_number=1
                    break
                elif second_number_str=='two':
                    second_number=2
                    break
                elif second_number_str=='ree':
                    if puzzle[i-4]+puzzle[i-3]+puzzle[i-2]+puzzle[i-1]+puzzle[i]=='three':
                        second_number=3
                        break
                    pass
                elif second_number_str=='our':
                    if puzzle[i-3]+puzzle[i-2]+puzzle[i-1]+puzzle[i]=='four':
                        second_number=4
                        break
                    pass
                elif second_number_str=='ive':
                    if puzzle[i-3]+puzzle[i-2]+puzzle[i-1]+puzzle[i]=='five':
                        second_number=5
                        break
                    pass
                elif second_number_str=='six':
                    second_number=6
                    break
                elif second_number_str=='ven':
                    if puzzle[i-4]+puzzle[i-3]+puzzle[i-2]+puzzle[i-1]+puzzle[i]=='seven':
                        second_number=7
                        break
                    pass
                elif second_number_str=='ght':
                    if puzzle[i-4]+puzzle[i-3]+puzzle[i-2]+puzzle[i-1]+puzzle[i]=='eight':
                        second_number=8
                        break
                    pass
                elif second_number_str=='ine':
                    if puzzle[i-3]+puzzle[i-2]+puzzle[i-1]+puzzle[i]=='nine':
                        second_number=9
                        break
                    pass
            pass
          
    number=first_number*10+second_number
    calibration.append(number)
    first_number=0
    second_number=0

df['Calibration']=calibration

df

                                      Puzzle  Calibration
0               ckmb52fldxkseven3fkjgcbzmnr7           57
1    gckhqpb6twoqnjxqplthree2fourkspnsnzxlz1           61
2                             2onetwocrgbqm7           27
3                  frkh2nineqmqxrvdsevenfive           25
4                                   four9two           42
..                                       ...          ...
995                     5ppflb48tkcffone8six           56
996              five2two7hstbbqzrninegbtwo2           52
997                           eightfblzpmhs4           84
998               fbbdeightzzsdffh8jbjzxkclj           88
999                              3nine6five1           31

[1000 rows x 2 columns]

In [4]:
df.Calibration.sum()

53312